export default function Head(): JSX.Element {
  return (
    <Head>
      <title>Next.js 13 stater template</title>
      <meta name="description" content="Next.js 13 stater template" />
      <meta name="description" content="Generated by create next" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
